export type HanjaRecommendedGrade = "3" | "4" | "5" | "6";

export type HanjaRecommendedWord = {
  word: string;
  note: string;
  category: string;
  level: number;
  definition: string;
  example: string;
  source: string;
};

export const HANJA_RECOMMENDED_WORDS: Record<HanjaRecommendedGrade, HanjaRecommendedWord[]> = {
  "3": [
    {
      word: "견학",
      note: "학교 밖 체험을 떠올리며 문장으로 확장하기 쉬워요.",
      category: "학교생활",
      level: 1,
      definition: "직접 현장에 가서 보고 배우는 즐거운 활동을 말해요.",
      example: "내일은 우리 반 모두가 과학관으로 견학을 가는 날이야.",
      source: "grade3_vocab.json",
    },
    {
      word: "과제",
      note: "학교생활과 연결된 경험 문장을 만들기 좋아요.",
      category: "학교생활",
      level: 1,
      definition: "선생님이 내주신 숙제나 우리가 꼭 해결해야 할 문제를 말해요.",
      example: "오늘 과제는 우리 동네의 멋진 장소를 조사해 오는 거야.",
      source: "grade3_vocab.json",
    },
    {
      word: "금지",
      note: "규칙과 약속에 관한 생활 문장을 만들기 좋아요.",
      category: "학교생활",
      level: 1,
      definition: "어떤 일을 하지 못하게 막는 규칙을 말해요.",
      example: "복도에서는 안전을 위해 뛰는 것이 금지되어 있어.",
      source: "grade3_vocab.json",
    },
    {
      word: "기후",
      note: "계절과 날씨를 설명하는 문장에 자연스럽게 이어져요.",
      category: "자연과 환경",
      level: 2,
      definition: "어떤 지역에서 오랫동안 나타나는 날씨의 평균적인 상태를 말해요.",
      example: "우리나라는 사계절이 뚜렷한 기후를 가지고 있어.",
      source: "grade3_vocab.json",
    },
    {
      word: "대화",
      note: "친구 관계와 소통 장면을 쓰기 쉬운 기본 어휘예요.",
      category: "사회와 소통",
      level: 1,
      definition: "서로 마주 보고 이야기를 주고받는 것을 말해요.",
      example: "짝꿍과 대화를 나누다 보니 서로 좋아하는 게임이 같다는 걸 알게 됐어.",
      source: "grade3_vocab.json",
    },
    {
      word: "문장",
      note: "글쓰기 활동과 바로 연결되는 핵심 어휘예요.",
      category: "말과 글",
      level: 1,
      definition: "생각이나 감정을 완벽하게 나타내는 글의 마디를 말해요.",
      example: "일기장에 오늘 있었던 일을 정성껏 한 문장씩 써 내려갔어.",
      source: "grade3_vocab.json",
    },
    {
      word: "안전",
      note: "학교와 생활 속 실천 문장을 만들기 좋아요.",
      category: "학교생활",
      level: 1,
      definition: "위험하지 않고 마음이 놓이는 편안한 상태를 말해요.",
      example: "자전거를 탈 때는 안전을 위해 꼭 헬멧을 써야 해.",
      source: "grade3_vocab.json",
    },
    {
      word: "역할",
      note: "모둠 활동이나 연극 경험을 써 보기 좋아요.",
      category: "사회와 소통",
      level: 2,
      definition: "자기가 맡은 일이나 해야 할 직분을 말해요.",
      example: "연극놀이에서 나는 나무 역할을 맡아 멋지게 서 있었어.",
      source: "grade3_vocab.json",
    },
    {
      word: "전통",
      note: "명절, 옷, 음식과 연결해 쓰기 좋은 문화 어휘예요.",
      category: "우리 역사",
      level: 2,
      definition: "옛날부터 오늘날까지 전해 내려오는 우리 고유의 것을 말해요.",
      example: "한복은 우리나라의 아름다운 전통 의상이야.",
      source: "grade3_vocab.json",
    },
    {
      word: "정보",
      note: "조사 활동이나 디지털 생활과 연결하기 쉬워요.",
      category: "과학과 기술",
      level: 2,
      definition: "우리가 어떤 일을 결정하는 데 도움이 되는 소식이나 자료를 말해요.",
      example: "인터넷에서 이번 주말 날씨 정보를 찾아보고 나들이 계획을 세웠어.",
      source: "grade3_vocab.json",
    },
    {
      word: "표현",
      note: "감정과 생각을 문장으로 드러내기 좋은 단어예요.",
      category: "감정과 태도",
      level: 1,
      definition: "생각이나 느낌을 말, 글, 그림 등으로 나타내는 거예요.",
      example: "사랑하는 마음을 편지로 표현해서 부모님께 드렸어.",
      source: "grade3_vocab.json",
    },
    {
      word: "장소",
      note: "언제 어디서 있었는지 쓰는 문장에 바로 활용돼요.",
      category: "사회와 소통",
      level: 1,
      definition: "어떤 일이 일어나거나 사람이 모이는 곳을 말해요.",
      example: "우리가 만나기로 한 장소는 학교 정문 앞이야.",
      source: "grade3_vocab.json",
    },
  ],
  "4": [
    {
      word: "관계",
      note: "친구, 가족, 모둠 사이를 설명하는 문장에 잘 맞아요.",
      category: "비교와 연결",
      level: 1,
      definition: "둘 이상의 사람이나 사물이 서로 연결되어 있는 상태를 말해요.",
      example: "나와 내 짝꿍은 서로 간식을 나눠 먹는 아주 사이좋은 관계예요.",
      source: "grade4_vocab.json",
    },
    {
      word: "구별",
      note: "비슷한 것을 나누어 설명하는 문장에 활용하기 좋아요.",
      category: "비교와 분류",
      level: 1,
      definition: "성질이나 모양에 따라 차이가 나는 것을 갈라내는 거예요.",
      example: "쌍둥이 형제는 얼굴이 아주 비슷해서 누가 누군지 구별하기 힘들어요.",
      source: "grade4_vocab.json",
    },
    {
      word: "근거",
      note: "이유를 들어 설명하는 문장으로 확장하기 좋아요.",
      category: "생각과 공부",
      level: 2,
      definition: "어떤 의견이나 주장을 뒷받침하는 확실한 이유나 바탕을 말해요.",
      example: "발표할 때는 내 주장이 맞다는 것을 보여줄 구체적인 근거를 들어야 해요.",
      source: "grade4_vocab.json",
    },
    {
      word: "목적",
      note: "왜 그 일을 하는지 쓰는 문장에 자연스럽게 이어져요.",
      category: "활동과 순서",
      level: 2,
      definition: "어떤 일을 하려고 하는 이유나 꼭 이루고 싶은 목표를 말해요.",
      example: "우리가 오늘 도서관에 모인 목적은 숙제를 같이 하기 위해서예요.",
      source: "grade4_vocab.json",
    },
    {
      word: "배경",
      note: "이야기와 경험의 시간, 장소를 설명하기 좋아요.",
      category: "말과 글",
      level: 2,
      definition: "이야기나 사건이 일어나는 시간과 장소를 말해요.",
      example: "이 동화책의 배경은 깊고 깊은 산속 작은 오두막집이에요.",
      source: "grade4_vocab.json",
    },
    {
      word: "상황",
      note: "지금 벌어지는 일을 정리해서 쓰기 좋은 단어예요.",
      category: "사회와 소통",
      level: 2,
      definition: "일이 벌어지고 있는 당시의 형편이나 모양새를 말해요.",
      example: "지금 교실 상황을 보니 모두가 독서에 집중하고 있군요.",
      source: "grade4_vocab.json",
    },
    {
      word: "소감",
      note: "체험 뒤 느낌을 문장으로 정리할 때 잘 맞아요.",
      category: "감정과 태도",
      level: 1,
      definition: "어떤 일을 겪은 뒤에 마음속에 일어나는 생각이나 느낌이에요.",
      example: "체험 학습을 다녀온 뒤에 느낀 점을 소감문으로 작성했어요.",
      source: "grade4_vocab.json",
    },
    {
      word: "의견",
      note: "토의와 발표 장면을 쓰기 좋은 대표 어휘예요.",
      category: "사회와 소통",
      level: 1,
      definition: "어떤 일에 대해 가지고 있는 나만의 생각이나 판단이에요.",
      example: "학급 회의 시간에 내 의견을 친구들 앞에서 당당하게 발표했어요.",
      source: "grade4_vocab.json",
    },
    {
      word: "참여",
      note: "함께 활동한 경험을 문장으로 만들기 좋아요.",
      category: "사회와 소통",
      level: 2,
      definition: "어떤 일에 직접 끼어들어 함께 활동하는 것을 말해요.",
      example: "우리 마을을 깨끗하게 만드는 봉사 활동에 모두가 참여했어요.",
      source: "grade4_vocab.json",
    },
    {
      word: "절차",
      note: "순서가 있는 활동을 설명하는 문장에 잘 맞아요.",
      category: "활동과 순서",
      level: 2,
      definition: "어떤 일을 하는 데 거쳐야 하는 순서나 단계를 말해요.",
      example: "도서관에서 책을 빌릴 때는 정해진 절차에 따라 회원증을 보여줘야 해요.",
      source: "grade4_vocab.json",
    },
    {
      word: "정확",
      note: "공부 습관과 태도를 쓰는 문장에 쓰기 편해요.",
      category: "생각과 공부",
      level: 1,
      definition: "조금도 틀림이 없이 바르고 확실한 상태를 말해요.",
      example: "수학 문제는 문제를 꼼꼼히 읽어야 정확한 답을 구할 수 있어요.",
      source: "grade4_vocab.json",
    },
    {
      word: "활용",
      note: "배운 내용을 실제로 써 본 경험을 적기 좋아요.",
      category: "활동과 순서",
      level: 2,
      definition: "알고 있는 지식이나 물건을 목적에 맞게 잘 써먹는 것을 말해요.",
      example: "수업 시간에 배운 내용을 활용해서 멋진 시를 한 편 썼어요.",
      source: "grade4_vocab.json",
    },
  ],
  "5": [
    {
      word: "감상",
      note: "책, 그림, 음악을 보고 느낀 점을 쓰기 좋아요.",
      category: "말과 글",
      level: 1,
      definition: "예술 작품을 보거나 듣고 마음속으로 느끼는 즐거움을 말해요.",
      example: "미술관에서 멋진 그림을 감상하며 내 생각을 정리해 보았어.",
      source: "grade5_vocab.json",
    },
    {
      word: "개선",
      note: "불편한 점을 바꾸는 실천 문장에 잘 어울려요.",
      category: "활동과 순서",
      level: 2,
      definition: "부족하거나 잘못된 점을 고쳐서 더 좋게 만드는 것을 말해요.",
      example: "급식 줄 서기 방법을 개선했더니 점심시간이 훨씬 여유로워졌어.",
      source: "grade5_vocab.json",
    },
    {
      word: "공감",
      note: "친구 마음을 이해하는 관계 문장에 자연스럽게 이어져요.",
      category: "감정과 태도",
      level: 1,
      definition: "상대방의 기분이나 생각이 나와 같다고 느끼는 따뜻한 마음이에요.",
      example: "슬퍼하는 친구의 마음을 공감해 주면 큰 위로가 된단다.",
      source: "grade5_vocab.json",
    },
    {
      word: "구조",
      note: "글이나 사물의 짜임을 설명하는 문장에 좋아요.",
      category: "말과 글",
      level: 2,
      definition: "여러 부분이 모여서 이루어진 전체적인 짜임새를 말해요.",
      example: "글의 전체적인 구조를 파악하면 내용을 이해하기가 훨씬 쉬워.",
      source: "grade5_vocab.json",
    },
    {
      word: "근거",
      note: "자기 생각을 설득력 있게 쓰는 데 필요한 단어예요.",
      category: "생각과 공부",
      level: 2,
      definition: "내 주장이나 의견이 맞다는 것을 보여주는 확실한 이유예요.",
      example: "발표할 때는 반드시 구체적인 근거를 들어서 친구들을 설득해야 해.",
      source: "grade5_vocab.json",
    },
    {
      word: "기행문",
      note: "체험학습이나 여행 경험을 글로 옮기기 좋아요.",
      category: "말과 글",
      level: 2,
      definition: "여행을 하며 보고 듣고 느낀 점을 기록한 글을 말해요.",
      example: "경주 여행을 다녀온 뒤에 즐거웠던 추억을 담아 기행문을 썼어.",
      source: "grade5_vocab.json",
    },
    {
      word: "문단",
      note: "글쓰기 구조를 생각하며 문장을 만들기 좋은 어휘예요.",
      category: "말과 글",
      level: 2,
      definition: "글에서 중심 생각을 나타내기 위해 문장들을 모아 놓은 덩어리예요.",
      example: "글을 쓸 때는 생각이 바뀔 때마다 문단을 나누어 주어야 해.",
      source: "grade5_vocab.json",
    },
    {
      word: "방안",
      note: "문제 해결 방법을 제안하는 문장에 잘 맞아요.",
      category: "생각과 공부",
      level: 2,
      definition: "문제를 해결하기 위해 세운 구체적인 계획이나 방법이에요.",
      example: "교실을 깨끗하게 만들기 위한 실천 방안을 모둠 친구들과 의논했어.",
      source: "grade5_vocab.json",
    },
    {
      word: "사건",
      note: "이야기 속 중요한 일을 중심으로 문장을 만들기 좋아요.",
      category: "활동과 순서",
      level: 2,
      definition: "이야기 속에서 등장인물들에게 일어나는 특별한 일을 말해요.",
      example: "동화책 속에서 주인공이 보물 지도를 발견하는 큰 사건이 벌어졌어.",
      source: "grade5_vocab.json",
    },
    {
      word: "조언",
      note: "선생님, 친구의 도움을 떠올리며 쓰기 좋아요.",
      category: "사회와 소통",
      level: 2,
      definition: "상대방에게 도움이 되도록 말해주는 충고나 가르침을 말해요.",
      example: "글쓰기가 힘들 때 선생님의 조언을 듣고 다시 시작할 수 있었어.",
      source: "grade5_vocab.json",
    },
    {
      word: "주장",
      note: "자기 생각을 분명하게 드러내는 문장에 적합해요.",
      category: "사회와 소통",
      level: 2,
      definition: "자기의 의견을 굽히지 않고 당당하게 내세우는 것을 말해요.",
      example: "학급 회의 시간에 급식 잔반을 줄여야 한다는 주장을 펼쳤어.",
      source: "grade5_vocab.json",
    },
    {
      word: "해결",
      note: "문제나 갈등을 풀어낸 경험을 쓰기 좋은 단어예요.",
      category: "생각과 공부",
      level: 1,
      definition: "어렵거나 복잡한 일을 잘 풀어서 마무리하는 거예요.",
      example: "수학 문제를 스스로 풀어서 해결했을 때 아주 기뻤어.",
      source: "grade5_vocab.json",
    },
  ],
  "6": [
    {
      word: "개발",
      note: "기술과 재능이 자라는 모습을 문장으로 쓰기 좋아요.",
      category: "과학과 기술",
      level: 2,
      definition: "새로운 기술을 만들거나 재능을 더 좋게 발전시키는 것을 말해요.",
      example: "컴퓨터 프로그래밍 실력을 개발해서 나만의 웹 앱을 만들 거야.",
      source: "grade6_vocab.json",
    },
    {
      word: "결론",
      note: "생각을 정리해서 마무리하는 문장에 잘 맞아요.",
      category: "말과 글",
      level: 2,
      definition: "말이나 글의 마지막 부분에서 내리는 최종적인 판단이나 요약이에요.",
      example: "논설문의 결론 부분에서 글쓴이의 주장을 다시 한번 강조했어.",
      source: "grade6_vocab.json",
    },
    {
      word: "결말",
      note: "이야기 끝부분을 떠올리며 쓰기 쉬운 어휘예요.",
      category: "말과 글",
      level: 1,
      definition: "이야기나 사건이 끝을 맺는 마지막 부분을 말해요.",
      example: "이 동화책은 주인공들이 행복하게 살게 되는 해피엔딩 결말이야.",
      source: "grade6_vocab.json",
    },
    {
      word: "공약",
      note: "학급 임원 선거나 약속 주제와 연결하기 좋아요.",
      category: "사회와 소통",
      level: 2,
      definition: "선거에 나선 사람이 당선되면 꼭 지키겠다고 국민이나 친구들에게 한 약속이에요.",
      example: "우리 반 회장 후보가 내세운 공약이 정말 실천 가능한지 따져보자.",
      source: "grade6_vocab.json",
    },
    {
      word: "극본",
      note: "연극과 발표 활동을 문장으로 확장하기 좋아요.",
      category: "말과 글",
      level: 2,
      definition: "연극을 하기 위해 배우의 대사와 행동 등을 미리 적어 놓은 글이에요.",
      example: "우리는 학예회 연극을 위해 재미있는 극본을 직접 썼어.",
      source: "grade6_vocab.json",
    },
    {
      word: "근거",
      note: "주장을 뒷받침하는 설득 문장에 꼭 필요한 단어예요.",
      category: "생각과 공부",
      level: 2,
      definition: "어떤 의견이나 주장이 맞다는 것을 뒷받침하는 확실한 이유예요.",
      example: "내 주장을 친구들이 믿게 하려면 타당한 근거를 들어야 해.",
      source: "grade6_vocab.json",
    },
    {
      word: "단서",
      note: "이야기와 추리 상황을 문장으로 만들기 좋아요.",
      category: "생각과 공부",
      level: 2,
      definition: "문제를 해결하거나 범인을 찾는 데 실마리가 되는 중요한 증거예요.",
      example: "범인이 남긴 작은 신발 자국이 사건을 푸는 결정적인 단서가 됐어.",
      source: "grade6_vocab.json",
    },
    {
      word: "당부",
      note: "부탁과 약속을 담은 생활 문장을 쓰기 좋아요.",
      category: "사회와 소통",
      level: 2,
      definition: "어떤 일을 꼭 해 달라고 간곡하게 부탁하는 거예요.",
      example: "선생님께서는 방학 동안 안전하게 지내라고 당부의 말씀을 하셨어.",
      source: "grade6_vocab.json",
    },
    {
      word: "매체",
      note: "신문, 영상, 인터넷 경험과 연결하기 쉬워요.",
      category: "사회와 소통",
      level: 2,
      definition: "소식이나 정보를 전달하기 위해 사용하는 신문, TV, 인터넷 등을 말해요.",
      example: "요즘은 영상 매체를 통해 새로운 지식을 배우는 친구들이 많아.",
      source: "grade6_vocab.json",
    },
    {
      word: "존중",
      note: "관계와 태도를 드러내는 문장을 만들기 좋아요.",
      category: "감정과 태도",
      level: 1,
      definition: "상대방을 소중하게 여기고 그 의견을 귀하게 대하는 태도예요.",
      example: "서로의 다름을 인정하고 존중하면 싸울 일이 훨씬 줄어든단다.",
      source: "grade6_vocab.json",
    },
    {
      word: "주제",
      note: "글이나 발표의 중심 생각을 쓰는 문장에 적합해요.",
      category: "말과 글",
      level: 2,
      definition: "글이나 말에서 나타내고자 하는 가장 핵심이 되는 생각이에요.",
      example: "글짓기를 할 때는 먼저 글의 주제를 정하는 것이 중요해.",
      source: "grade6_vocab.json",
    },
    {
      word: "문화",
      note: "전통, 나라, 생활 방식을 비교하며 쓰기 좋아요.",
      category: "사회와 소통",
      level: 1,
      definition: "사람들이 오랜 시간 함께 살아가며 만들어낸 고유한 생활 방식이나 예술이에요.",
      example: "나라마다 먹는 음식과 입는 옷 등 서로 다른 문화를 가지고 있어.",
      source: "grade6_vocab.json",
    },
  ],
};
